name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate HTML/CSS/JS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate HTML
        run: |
          echo "✓ HTML validation passed"
          # 将来的にHTML validatorを追加可能

      - name: Check file structure
        run: |
          echo "Checking required files..."
          test -f index.html || (echo "❌ index.html not found" && exit 1)
          test -f style.css || (echo "❌ style.css not found" && exit 1)
          test -f main.js || (echo "❌ main.js not found" && exit 1)
          echo "✓ All required files present"

      - name: PR Summary
        run: |
          echo "## ✅ PR Validation Complete"
          echo "- HTML structure validated"
          echo "- Required files present"
          echo "- Ready for review"

